module.exports = (sequelize, DataTypes) => {
  return sequelize.define('User', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    full_name: DataTypes.STRING,
    role_name: DataTypes.STRING,
    role_id: DataTypes.INTEGER,
    organ_id: DataTypes.INTEGER,
    mobile: DataTypes.STRING,
    email: { type: DataTypes.STRING, unique: true },
    bio: DataTypes.TEXT,
    password: DataTypes.STRING,
    google_id: DataTypes.STRING,
    facebook_id: DataTypes.STRING,
    remember_token: DataTypes.STRING,
    verified: DataTypes.BOOLEAN,
    financial_approval: DataTypes.BOOLEAN,
    avatar: DataTypes.STRING,
    avatar_settings: DataTypes.STRING,
    cover_img: DataTypes.STRING,
    about: DataTypes.TEXT,
    address: DataTypes.STRING,
    country_id: DataTypes.INTEGER,
    province_id: DataTypes.INTEGER,
    city_id: DataTypes.INTEGER,
    district_id: DataTypes.INTEGER,
    location: DataTypes.GEOMETRY('POINT'),
    level_of_training: DataTypes.ENUM('1', '2', '3'),
    meeting_type: DataTypes.ENUM('all', 'in_person', 'online'),
    status: { type: DataTypes.ENUM('active', 'pending', 'inactive'), defaultValue: 'pending' },
    access_content: DataTypes.STRING,
    language: DataTypes.STRING,
    newsletter: DataTypes.BOOLEAN,
    public_message: DataTypes.BOOLEAN,
    account_type: DataTypes.STRING,
    account_id: DataTypes.STRING,
    certificate: DataTypes.STRING,
    commission: DataTypes.STRING,
    affiliate: DataTypes.BOOLEAN,
    can_create_store: DataTypes.BOOLEAN,
    ban: DataTypes.STRING,
    ban_start_at: DataTypes.DATE,
    ban_end_at: DataTypes.DATE,
    offline_message: DataTypes.TEXT,
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE,
    school_id: DataTypes.INTEGER,
    section_id: DataTypes.INTEGER,
    level_id: DataTypes.INTEGER,
    otp: DataTypes.STRING,
    otpExpires: DataTypes.DATE
  }, {
    tableName: 'users',
    timestamps: false
  });
};